// Chatbot Q&A Batch 3 — Building & Construction Trades
// 5 trades × 15–16 questions each = 78 entries
// Topics: websites, SEO, local SEO, paid ads, branding, social media, lead quality, seasonal demand, trust signals, photos, reviews, service pages, missed calls, automation

window.QA_BATCH3 = [
  // ROOFING CONTRACTORS (16 questions)
  {
    id: "B3-ROOF-001",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "Why should roofing contractors have a website?",
    alts: ["Do I need a website as a roofer?", "Is a website worth it for my roofing business?"],
    shortA: "Your website is your 24/7 salesman. Homeowners research roofers online before calling — your site builds trust, shows past work, displays reviews, and captures leads while you're on the job.",
    fullA: "A roofing website does three things: (1) It gets found by people searching 'roofer near me' or 'roof repair [your city]' in an emergency. (2) It showcases before-and-after photos of completed jobs — the strongest proof of quality. (3) It collects reviews, certifications, and insurance info in one place, so customers trust you before they dial. Without a site, your competitor gets the call.",
    followUp: "Want to see examples of roofing websites that convert leads into calls?",
    intent: "Awareness",
    emotion: "Skeptical, Busy",
    leadValue: "High",
    cta: "View Roofing Website Examples",
    relatedService: "Websites + Local SEO",
    escalate: false,
    tags: ["roofing", "website", "leads", "trust", "conversions"],
    notes: "Emphasize lead capture during emergencies (storms, leaks). Roofing is seasonal and weather-driven."
  },
  {
    id: "B3-ROOF-002",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "How do I get more roof repair calls in my local area?",
    alts: ["How can I rank higher on Google for roof repairs?", "Why aren't people finding my roofing business online?"],
    shortA: "Google Local SEO — optimize your Google Business Profile, get reviews, add location pages, and ensure your name, address, phone match everywhere. Roofers who rank locally get 3–4× more calls.",
    fullA: "Roofing is local. Your customer doesn't want the 'best roofer in America' — they want YOU because you're 10 minutes away. We set up your Google Business profile correctly, add service-area pages for each neighborhood, collect reviews (especially after emergency repairs), and make sure your phone number and address are consistent everywhere online. Local SEO for roofers typically brings calls within 30 days.",
    followUp: "How many reviews do you have right now?",
    intent: "Problem-Solving",
    emotion: "Frustrated, Urgency",
    leadValue: "High",
    cta: "Get Local SEO Audit",
    relatedService: "Local SEO + Google Business",
    escalate: false,
    tags: ["roofing", "local seo", "google maps", "reviews", "emergency calls"],
    notes: "Roofing emergencies (storms, leaks) drive urgent searches. Reviews are critical trust signals."
  },
  {
    id: "B3-ROOF-003",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "What if I get calls but they don't turn into jobs?",
    alts: ["Leads call but don't book — what's wrong?", "How do I convert more roof inquiries into appointments?"],
    shortA: "Two issues: your website may not build enough trust (photos, reviews, certifications missing), or you're missing calls because you're on the roof. Automation + call answering closes those gaps.",
    fullA: "Roofers lose sales two ways: (1) Leads call but your site doesn't have enough proof (no photos of completed jobs, no reviews, insurance not listed) — they hang up and call a competitor. (2) You're actually on the job, so you miss calls entirely. We fix this with: (a) a robust website with lots of before-and-after photos and 4.8+ reviews, (b) a call-answering AI that schedules appointments 24/7, and (c) text-message follow-up for missed calls. You work; the system sells.",
    followUp: "How many calls do you estimate you're missing right now?",
    intent: "Problem-Solving",
    emotion: "Frustrated, Loss-Averse",
    leadValue: "High",
    cta: "Get Call-Capture Audit",
    relatedService: "Websites + AI Automations",
    escalate: false,
    tags: ["roofing", "conversion", "missed calls", "trust signals", "automation"],
    notes: "Roofers are often on-site during business hours. Automation is critical."
  },
  {
    id: "B3-ROOF-004",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "Should I pay for roofing ads on Google or Facebook?",
    alts: ["Are roofing ads worth the money?", "How much should I spend on roofing ads?"],
    shortA: "Paid ads work IF your website and phone system are ready. A strong website + great reviews + call answering = ROI. Without those, you'll waste money. We build both together.",
    fullA: "Paid ads (Google Ads, Facebook) put your business in front of homeowners actively searching for roofers. BUT: if your website doesn't have before-and-afters, recent reviews, or clear pricing info, they'll click away. And if you can't answer calls, the lead dies. We recommend: (1) Fix your website first. (2) Get 15+ recent reviews. (3) Set up call handling. (4) THEN run ads. Budget: $800–2000/month to start, scaling as you get profitable leads. Average roofing job is $4000–$15000, so ROI is strong if you're ready.",
    followUp: "How many leads do you get per month right now?",
    intent: "Consideration",
    emotion: "Curious, Cost-Conscious",
    leadValue: "Medium",
    cta: "Get Free Roofing Ads Audit",
    relatedService: "Paid Ads + Website",
    escalate: false,
    tags: ["roofing", "paid ads", "google ads", "facebook", "roi", "budget"],
    notes: "Roofing has high job values. Paid ads are viable but require operational readiness."
  },
  {
    id: "B3-ROOF-005",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "How do I show my roofing work online without professional photos?",
    alts: ["Can I use phone photos for my roofing website?", "Do I need a professional photographer?"],
    shortA: "Phone photos work — we just need 10–15 good before-and-afters from recent jobs. We'll edit and optimize them for your site. Professional is nice but not required.",
    fullA: "Homeowners want to SEE completed roofs. Phone photos from your jobs are perfect — honest, real, timely. We'll: (1) Help you organize your best shots (clear daylight photos, ideally with house visible for context), (2) Light touch of editing to make colors pop, (3) Add captions like 'Storm damage repair, Quad Cities' to help with SEO. If you do a few jobs per week, you'll have a fresh library in 2–3 months. No fancy photographer needed.",
    followUp: "How many before-and-after photos do you have right now?",
    intent: "Awareness",
    emotion: "Practical, Cost-Conscious",
    leadValue: "Medium",
    cta: "Start Building Your Photo Library",
    relatedService: "Websites + Branding",
    escalate: false,
    tags: ["roofing", "photography", "before-and-after", "website content"],
    notes: "Roofers often have phone photos from job sites. Encourage ongoing photo collection."
  },
  {
    id: "B3-ROOF-006",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "Do roofing reviews really matter?",
    alts: ["How important are Google reviews for roofers?", "Will reviews help me get more calls?"],
    shortA: "Yes. 92% of homeowners read reviews before hiring. Even one bad review kills deals. We help you collect and manage reviews automatically.",
    fullA: "A roofer with 4.8 stars and 47 reviews gets 5–10× more calls than one with zero reviews. Reviews signal: (1) You're real and established, (2) You finish jobs, (3) Your customers are happy. Every job is a review opportunity. We set up text-message and email requests after completion, so customers leave reviews without you asking three times. One 1-star review? We help you respond professionally and address the issue. Reviews take time but they're your #1 sales tool.",
    followUp: "How many reviews do you have on Google right now?",
    intent: "Problem-Solving",
    emotion: "Concerned, Determined",
    leadValue: "High",
    cta: "Audit Your Reviews",
    relatedService: "Review Management + Local SEO",
    escalate: false,
    tags: ["roofing", "reviews", "reputation", "trust", "google stars"],
    notes: "Roofing industry heavily review-driven. Recent reviews matter most (within 6 months)."
  },
  {
    id: "B3-ROOF-007",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "How do I handle missed calls when I'm on a roof?",
    alts: ["What do I do when I miss roofing calls?", "Should I hire a receptionist?"],
    shortA: "Don't hire a receptionist. Use an AI call answerer — it schedules appointments 24/7, texts you summaries, and you call them back. Costs $200–400/month, saves thousands in lost jobs.",
    fullA: "Here's the reality: you're on a roof at 2 PM, phone rings, you can't answer, customer hangs up and calls another roofer. AI call answering fixes this. Our system answers on the second ring, takes the customer's info, schedules an appointment right there, and texts you a summary. You call them back within 2 hours. Customers LOVE this — it feels professional and they get instant confirmation. No hiring, no payroll, no drama. ROI is immediate: one extra job per month ($5000+) pays for the whole year.",
    followUp: "How many calls do you get per day on average?",
    intent: "Problem-Solving",
    emotion: "Busy, Practical",
    leadValue: "High",
    cta: "See Call-Answering Demo",
    relatedService: "AI Automations",
    escalate: false,
    tags: ["roofing", "call answering", "ai", "scheduling", "automation", "missed calls"],
    notes: "Roofers spend most of day on-site. AI answering is essential, not optional."
  },
  {
    id: "B3-ROOF-008",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "How do I find customers in neighborhoods I want to target?",
    alts: ["How do I get jobs in specific areas?", "Can I target certain zip codes?"],
    shortA: "Service-area pages + local ads. We build a page for each neighborhood, optimize it for 'roofer in [neighborhood name]', and run ads in those areas. You control where you work.",
    fullA: "Maybe you want jobs in East Side and Upland Hills, not Clear Lake. We create dedicated service-area pages for each neighborhood with local info, photos of completed jobs in that area, and local testimonials. Google ranks these pages for 'roofer in East Side' searches. Combined with Google Local ads targeting those zip codes, you'll dominate those neighborhoods. You decide your service area; we make sure those homeowners find you.",
    followUp: "Which neighborhoods or zip codes do you prefer?",
    intent: "Consideration",
    emotion: "Strategic, Practical",
    leadValue: "Medium",
    cta: "Map Your Service Areas",
    relatedService: "Local SEO + Service-Area Pages",
    escalate: false,
    tags: ["roofing", "local seo", "service areas", "neighborhoods", "targeting"],
    notes: "Roofers often have service-area preferences. Service-area pages are high-ROI."
  },
  {
    id: "B3-ROOF-009",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "Is roofing seasonal? How do I stay busy year-round?",
    alts: ["How do I get roofing jobs in winter?", "What if business slows down?"],
    shortA: "Yes, roofing is seasonal (storm season = peak). We market year-round with ads and SEO so off-season calls still come in. Some roofers offer 'off-season specials' to stay busy.",
    fullA: "Storm season (spring/summer) drives 60–70% of roofing revenue. Winter is slower. Smart roofers: (1) Build a review backlog during peak season so winter leads still call, (2) Run 'winter roof inspection' or 'ice-dam removal' ads, (3) Offer discounts for off-season jobs to keep crews working. Digital marketing smooths the seasonal curve — you're visible year-round, not just when it storms. Plus, homeowners planning spring reroof jobs start researching in February.",
    followUp: "When is your busiest season and your slowest?",
    intent: "Problem-Solving",
    emotion: "Practical, Concerned",
    leadValue: "Medium",
    cta: "Discuss Year-Round Strategy",
    relatedService: "Seasonal Marketing Strategy",
    escalate: true,
    escalateReason: "Roofing seasonality requires a custom year-round marketing plan. This is a strategy conversation, not a standard Q&A.",
    tags: ["roofing", "seasonal", "marketing strategy", "revenue", "storm season"],
    notes: "Roofing is highly seasonal. Some roofers expand to gutter/siding during off-season."
  },
  {
    id: "B3-ROOF-010",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "What certifications and insurance should I display on my website?",
    alts: ["Should I put my license number online?", "How do I build trust with certifications?"],
    shortA: "Yes. Display your license, insurance (liability + workers' comp), manufacturer certifications (GAF, Owens Corning, etc.), and bonding. Homeowners check these before hiring.",
    fullA: "A homeowner hiring a roofer is betting on: (1) You'll finish the job, (2) You'll do it right, (3) You're insured if something goes wrong. Display: (1) State roofing license (number + status), (2) General liability insurance, (3) Workers' compensation (required in most states), (4) Manufacturer certifications (proves training), (5) Bonding (if available). Don't just list them — photograph your actual license and insurance card. Adds credibility instantly. This info turns website visitors into callers.",
    followUp: "Do you have all your certifications and insurance docs ready to upload?",
    intent: "Awareness",
    emotion: "Practical, Serious",
    leadValue: "High",
    cta: "Get Website Trust-Building Checklist",
    relatedService: "Websites + Branding",
    escalate: false,
    tags: ["roofing", "trust signals", "certifications", "insurance", "license", "credibility"],
    notes: "Trust signals are critical for high-value trades like roofing. Homeowners verify credentials."
  },
  {
    id: "B3-ROOF-011",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "Should I post on Facebook or Instagram? Which is better for roofers?",
    alts: ["Is social media worth it for roofing?", "Do I need Instagram and Facebook?"],
    shortA: "Yes, but differently. Facebook for older homeowners (ad targeting + community posts). Instagram for before-and-afters. Post 1–2× per week of completed jobs. It builds brand, not immediate leads.",
    fullA: "Facebook: Homeowners 40+ hang out here. Run local ads ('roofer in Quad Cities') and post community updates ('Storm damage free inspections'). Instagram: Visual platform — post beautiful before-and-after photos with short captions. Both build your brand. Neither replaces your website or Google Local SEO for getting calls immediately. Think of it as '3rd-party credibility' — people see your work on their feed, then they're more confident when they visit your website. Time: 30 mins/week per platform. Cost: free posts (organic), $200–500/month if running ads.",
    followUp: "Do you have a bunch of great before-and-afters you could share weekly?",
    intent: "Awareness",
    emotion: "Curious, Skeptical",
    leadValue: "Low",
    cta: "Get Social Media Starter Plan",
    relatedService: "Branding + Social Media",
    escalate: false,
    tags: ["roofing", "social media", "facebook", "instagram", "before-and-after", "branding"],
    notes: "Social media builds brand; doesn't replace SEO/ads for immediate lead generation."
  },
  {
    id: "B3-ROOF-012",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "How do I know my marketing is working? What should I measure?",
    alts: ["How do I track roofing leads?", "What metrics matter for roofers?"],
    shortA: "Track: (1) Calls received, (2) Calls that became jobs, (3) Average job value, (4) Cost-per-lead. We give you a dashboard. If your cost-per-lead is < 10% of average job, you're winning.",
    fullA: "You need data. Here's what matters: (1) How many calls per month (from all sources), (2) What % convert to site visits/appointments, (3) What % of appointments become jobs, (4) Average job value. Example: If you get 100 calls/month, 30 turn into jobs, and average job is $8000, you're making $240k/month from those calls. If you spend $500/month on marketing, cost-per-lead is ~$17 — fantastic ROI. We set up a dashboard showing these numbers in real-time. No guessing. You'll know what's working and what to double down on.",
    followUp: "How do you currently track where your calls come from?",
    intent: "Problem-Solving",
    emotion: "Practical, Data-Driven",
    leadValue: "Medium",
    cta: "Get Custom Reporting Dashboard",
    relatedService: "Analytics + Reporting",
    escalate: false,
    tags: ["roofing", "tracking", "metrics", "roi", "reporting", "data"],
    notes: "Roofers often don't track metrics. A simple dashboard transforms business decisions."
  },
  {
    id: "B3-ROOF-013",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "What if my competitor has a better website than me?",
    alts: ["My competitor outranks me on Google. What do I do?", "How do I beat my competitor online?"],
    shortA: "Don't panic. Outrank them with more reviews, better local SEO (service-area pages), and paid ads in their blind spots. We do competitive audits to find opportunities.",
    fullA: "If a competitor's website is better, it's usually because they have: (1) More reviews (4.8 stars vs. your 4.2), (2) Better photos (they invested in before-and-afters), (3) Stronger local SEO (they're optimized for your town + neighborhoods). We do a free competitive audit: we analyze their strengths, find YOUR advantages, and build a plan to beat them. Maybe they're not in neighborhood X yet — we dominate there. Maybe they have 30 reviews — we get you 50 in 6 months. You don't copy them; you beat them at specific plays.",
    followUp: "Who do you view as your main competitor?",
    intent: "Problem-Solving",
    emotion: "Competitive, Concerned",
    leadValue: "High",
    cta: "Get Competitive Audit",
    relatedService: "Competitive Analysis + Strategy",
    escalate: true,
    escalateReason: "Competitive strategy requires custom analysis and planning. Escalate for deeper conversation.",
    tags: ["roofing", "competition", "seo", "reviews", "strategy"],
    notes: "Roofers often feel outgunned by larger competitors. Position Toughjobs as the strategy fix."
  },
  {
    id: "B3-ROOF-014",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "Do I need a phone system upgrade for roofing leads?",
    alts: ["Should I get a business phone number?", "Can I use my cell phone for roofing inquiries?"],
    shortA: "Yes. A professional business number (local) + call recording for quality control is standard. Pair it with call answering AI and you're golden. It costs ~$50–100/month.",
    fullA: "Using your personal cell looks small. A local business number signals 'established company.' Roofing customers expect to reach a business, not a personal phone. We set up: (1) Local number in your area, (2) Call routing (rings to your phone, then answering AI after-hours), (3) Recording for training/disputes, (4) Call analytics (which marketing source brought this call?). Total cost: ~$50–100/month. Roi: One extra booked job per month pays for a year of service.",
    followUp: "What phone number do customers call now?",
    intent: "Awareness",
    emotion: "Practical, Professional",
    leadValue: "Medium",
    cta: "Upgrade Your Phone System",
    relatedService: "Phone Systems + AI Automations",
    escalate: false,
    tags: ["roofing", "phone system", "business number", "call handling", "professionalism"],
    notes: "Professional phone system is low-cost, high-impact for trades."
  },
  {
    id: "B3-ROOF-015",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "Can you guarantee I'll get X roofing jobs per month?",
    alts: ["What if your marketing doesn't work?", "Do you have a guarantee?"],
    shortA: "No guarantee on 'X jobs' — too many variables (price, service area, crew size). But we guarantee leads. Our standard: if we don't double your lead flow in 90 days, we refund your first month.",
    fullA: "Here's why: We can't control if YOU close a lead. That's sales, not marketing. But we GUARANTEE to bring qualified calls and leads to your site. If you're currently getting 10 calls/month, we commit to 20+ in 90 days — or we refund your first month's fee. We're confident because we've done this for roofing companies. What we need from you: (1) A good website (we build it), (2) Answer your phone or use our AI answerer, (3) Show up to estimate appointments. Do that, and leads will come.",
    followUp: "What's your current call/lead volume?",
    intent: "Consideration",
    emotion: "Skeptical, Risk-Averse",
    leadValue: "High",
    cta: "See Our Guarantee",
    relatedService: "Performance Guarantee",
    escalate: true,
    escalateReason: "Guarantees require a custom conversation about the client's specific business situation and metrics.",
    tags: ["roofing", "guarantee", "risk", "results", "leads"],
    notes: "Roofing roofers worry about wasting money. Lead guarantee builds confidence."
  },
  {
    id: "B3-ROOF-016",
    mainCat: "Building & Construction",
    serviceCat: "Roofing",
    tradeCat: "Roofing",
    trade: "Roofing Contractors",
    q: "What about roofing fleet wraps for my trucks?",
    alts: ["Should I wrap my roofing trucks?", "Is a vehicle wrap worth it for roofers?"],
    shortA: "Yes. A wrapped truck is a moving billboard — 5000+ people see it daily. Roofing wraps cost $2500–4000, ROI is 2–3 months. Your website URL + reviews should be on the wrap.",
    fullA: "Your truck is already driving around town. A wrap with your business name, phone, website, and 2–3 photos of completed roofs turns it into a lead-generating machine. Every stop light, every drive past a house that needs a roof — you're advertising. Cost: $2500–4000 per truck for professional wrap. ROI: One extra job from a wrap driver per month pays for the wrap in 2.5 months. Most roofers see 2–3 extra jobs per truck per month. We design wraps that match your brand, highlight your best before-and-afters, and include a QR code linking to your website.",
    followUp: "How many trucks do you have?",
    intent: "Consideration",
    emotion: "Practical, Interested",
    leadValue: "Medium",
    cta: "See Roofing Wrap Designs",
    relatedService: "Branding + Fleet Wraps",
    escalate: false,
    tags: ["roofing", "fleet wraps", "vehicle wrap", "branding", "advertising"],
    notes: "Fleet wraps are powerful for local visibility. Include website + strong visuals."
  },

  // GENERAL CONTRACTORS (15 questions)
  {
    id: "B3-GC-001",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "As a general contractor, why do I need a website?",
    alts: ["Do GCs really need websites?", "I get jobs from referrals — do I still need a site?"],
    shortA: "Referrals are gold, but a website turns them into conversations. People Google you before referring a friend. A strong site proves you're legitimate, shows past projects, and builds your reputation.",
    fullA: "Here's the reality: 60% of referrals start with a Google search. Your potential client says 'I know a great GC but let me check them out online first.' If you have no website, you look small or out of business. Your site doesn't replace referrals — it amplifies them. It says: (1) I'm established (you have testimonials), (2) I do quality work (project photos), (3) I'm legit (license, bonding, insurance). A good website also captures NEW leads from Google — people searching 'general contractor [your area]' who found you through search, not word-of-mouth.",
    followUp: "Do most of your jobs come from referrals right now?",
    intent: "Awareness",
    emotion: "Practical, Confident",
    leadValue: "High",
    cta: "See GC Website Examples",
    relatedService: "Websites",
    escalate: false,
    tags: ["gc", "general contractor", "website", "referrals", "credibility"],
    notes: "GCs often rely on referrals but underestimate online credibility. Website amplifies word-of-mouth."
  },
  {
    id: "B3-GC-002",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How do I get leads beyond referrals?",
    alts: ["How do I find new clients without asking for referrals?", "Can I grow without relying on word-of-mouth?"],
    shortA: "Google Local SEO + paid ads. Homeowners search 'general contractor near me' + your address area. We optimize your local presence so you get found before you're referred.",
    fullA: "Referrals are great but capped — your network can only refer so many jobs. Growth requires reaching NEW customers who don't know you yet. We use: (1) Google Local SEO (your business shows up for 'GC [your city]' searches), (2) Service-area pages (you dominate specific neighborhoods), (3) Paid ads during renovation season. You'll get calls from people actively planning projects, not just people you know. Biggest source? Google searches spike during home-improvement season (spring/summer). Be visible then, and you'll be busy.",
    followUp: "What % of your current jobs come from outside your referral network?",
    intent: "Problem-Solving",
    emotion: "Ambitious, Growth-Minded",
    leadValue: "High",
    cta: "Get GC Lead Generation Plan",
    relatedService: "Local SEO + Paid Ads",
    escalate: false,
    tags: ["gc", "general contractor", "leads", "seo", "growth"],
    notes: "GCs can grow beyond referrals with targeted local marketing. The market is there."
  },
  {
    id: "B3-GC-003",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How important are before-and-after photos for a GC website?",
    alts: ["What project photos should I include?", "Do I need professional photography?"],
    shortA: "Critical. Before-and-afters prove capability. Phone photos work fine — 15–20 projects from different categories (kitchens, bathrooms, decks, additions). Have them ready and update quarterly.",
    fullA: "A homeowner considering a $50k kitchen remodel wants to see what you've done. Before-and-afters are proof. You don't need a fancy photographer — take them yourself with good daylight, straight angles, and clear visibility of both rooms. Categories to show: (1) Full remodels (kitchen, bath), (2) Additions/expansions, (3) Specialty work (decks, custom details), (4) Quick turnarounds (small projects). Update quarterly with new jobs. This portfolio is your strongest sales tool. We'll optimize them for search and display them beautifully on your site.",
    followUp: "How many good project photos do you have ready right now?",
    intent: "Awareness",
    emotion: "Practical, Quality-Focused",
    leadValue: "High",
    cta: "Start Building Project Portfolio",
    relatedService: "Websites + Photography",
    escalate: false,
    tags: ["gc", "general contractor", "before-and-after", "portfolio", "website"],
    notes: "GCs are visual. A strong portfolio is their #1 sales asset on the website."
  },
  {
    id: "B3-GC-004",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "Should I post my pricing on my website?",
    alts: ["Should I list how much projects cost?", "Is pricing transparency good for GCs?"],
    shortA: "No. GC projects are custom — every kitchen remodel is different. Instead, show pricing ranges ('Kitchens: $30k–$75k') and offer a FREE consultation. Pricing on-site kills conversations.",
    fullA: "Every project is unique — square footage, materials, timeline, complexity. A homeowner sees '$50k kitchen' but theirs might be $30k or $80k. Showing exact prices scares people away. Instead: (1) Show RANGES ('Most kitchens: $35k–$65k'), (2) Emphasize FREE consultation ('We'll assess your project and give an exact estimate'), (3) List value drivers ('high-end finishes, timeline, design complexity'). This keeps curious people on your site and calling you instead of leaving for a competitor who posts cheaper numbers.",
    followUp: "Are you comfortable discussing pricing on a consultation call instead?",
    intent: "Consideration",
    emotion: "Practical, Professional",
    leadValue: "Medium",
    cta: "Get Pricing Strategy Guide",
    relatedService: "Website Strategy",
    escalate: false,
    tags: ["gc", "general contractor", "pricing", "website", "strategy"],
    notes: "Custom pricing requires custom consultations. Ranges work; exact prices don't."
  },
  {
    id: "B3-GC-005",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How do I manage leads and follow up when I'm on job sites?",
    alts: ["I miss calls when I'm working. How do I fix it?", "Should I hire someone to manage leads?"],
    shortA: "Use a CRM (customer relationship tool) + call answering AI. Leads auto-log, you see them on your phone, and AI schedules calls. $200–400/month beats hiring someone.",
    fullA: "You're on a job site → phone rings → you miss it → lead goes cold. Solution: (1) AI call answering takes the inquiry and schedules a time for YOU to call back, (2) All leads go into a CRM (simple tracking), (3) Reminders so you don't forget follow-up. You'll call back 50+ qualified prospects per month, instead of losing them. Small investment, huge impact on closing rate. Most GCs who implement this see 20–30% more closed jobs.",
    followUp: "How many calls/week do you get that you can't answer?",
    intent: "Problem-Solving",
    emotion: "Busy, Overwhelmed",
    leadValue: "High",
    cta: "See Lead Management Demo",
    relatedService: "CRM + AI Automations",
    escalate: false,
    tags: ["gc", "general contractor", "crm", "automation", "lead management", "follow-up"],
    notes: "GCs juggle job sites and sales. Automation prevents lead loss."
  },
  {
    id: "B3-GC-006",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How do I build trust as a newer GC without a big portfolio?",
    alts: ["I'm new to general contracting. How do I get credibility?", "No references yet — what do I do?"],
    shortA: "Show: (1) License & insurance prominently, (2) Any certifications, (3) Process transparency (testimonials from first few clients), (4) Before-and-afters of your best early jobs. Build fast via quality.",
    fullA: "You can't fake experience, but you can show professionalism. Day 1: Get your license, liability insurance, and bonding in place. Display these visibly on your site. Day 2: Do amazing work on your first 3–5 projects. Get reviews. Photograph everything. Day 3: Write about your process ('Our 7-step approach'), speak to quality, show client testimonials even if it's just 3 people. Many homeowners prefer a new, hungry GC over a complacent veteran. Use that. Your website should say: 'We're new, we're licensed, we're insured, we do stellar work.' You'll get jobs.",
    followUp: "Do you have your license and insurance in place?",
    intent: "Awareness",
    emotion: "Eager, Uncertain",
    leadValue: "Medium",
    cta: "Get New GC Credibility Checklist",
    relatedService: "Branding + Trust Signals",
    escalate: false,
    tags: ["gc", "general contractor", "new business", "credibility", "trust", "license"],
    notes: "New GCs often worry about credibility. Focus on professionalism + quality proof."
  },
  {
    id: "B3-GC-007",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "Should I specialize or stay general?",
    alts: ["Should I focus on kitchens or do everything?", "Does specialization help with marketing?"],
    shortA: "Specialization = higher pricing + easier marketing. 'GC' is vague; 'kitchen remodel expert' is clear. You can still do other work, but focus your marketing on your strongest service.",
    fullA: "Here's the business reality: A homeowner choosing between a 'general contractor' and a 'kitchen remodel specialist' will pay MORE and trust MORE the specialist. Marketing works the same way. If we position you as the 'master kitchen remodel GC in Quad Cities,' you'll dominate that keyword, charge premium prices, and get 2–3 inquiries per month just from that focus. You still do bathrooms and decks, but your website, ads, and messaging lead with kitchens. Higher perceived value, higher closing rate. As you grow, add specialties. Start with your strongest skill.",
    followUp: "What type of project do you most enjoy and where do you make the best margin?",
    intent: "Consideration",
    emotion: "Strategic, Practical",
    leadValue: "High",
    cta: "Discuss Positioning Strategy",
    relatedService: "Branding + Positioning",
    escalate: true,
    escalateReason: "Specialization strategy is a core business conversation, not a simple Q&A.",
    tags: ["gc", "general contractor", "specialization", "positioning", "marketing", "strategy"],
    notes: "Specialization is counter-intuitive but powerful for GC marketing."
  },
  {
    id: "B3-GC-008",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "What should my website pricing/estimate process look like?",
    alts: ["How do I handle price inquiries on my website?", "Should I offer online quotes?"],
    shortA: "Offer a FREE in-person or video consultation. Site inspection is crucial for accurate GC estimates. Online quotes look cheap and lose credibility.",
    fullA: "A homeowner wants a $40k kitchen. They see 'Get Quote' button, fill a form, get an instant number. That's for fast-food, not remodeling. Your process: (1) Click 'Schedule Consultation,' (2) You visit their home (or video call), (3) You understand their vision, budget, timeline, (4) You send a detailed estimate. This approach: (a) Qualifies the lead (you don't waste time on tire-kickers), (b) Builds relationship (they trust you've listened), (c) Commands premium pricing (you're positioned as expert, not commodity). Make scheduling easy on your site, but don't give away estimates without conversation.",
    followUp: "How long does your average consultation take?",
    intent: "Problem-Solving",
    emotion: "Professional, Focused",
    leadValue: "High",
    cta: "See Consultation Process Template",
    relatedService: "Website + Sales Process",
    escalate: false,
    tags: ["gc", "general contractor", "estimates", "consultation", "process", "sales"],
    notes: "GC estimates are consultations, not instant quotes. Online processes should reflect that."
  },
  {
    id: "B3-GC-009",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How do I stay top-of-mind with past clients for repeat work and referrals?",
    alts: ["How do I keep past clients as repeat customers?", "How do I turn clients into referral machines?"],
    shortA: "Email + value. Send 1–2 emails/month with home-improvement tips, seasonal checklists, new project ideas. After a completed job, ask for a review. 70% of best jobs come from past clients.",
    fullA: "Past clients are your goldmine. They trust you, they know your quality, and they live in YOUR market (they know other homeowners who might need remodels). System: (1) Every time you finish a project, ask for a Google review + referral incentive (small gift/discount). (2) Monthly email (Home Care Tips, 'Is Your Kitchen Next?', seasonal checklist). (3) Annual 'Maintenance Inspection' offer (free review of past work). (4) Follow up on project anniversaries ('It's been 2 years — how's your kitchen holding up?'). These touches keep you top-of-mind. Result: Repeat jobs + referrals = 60–70% of pipeline, lowest acquisition cost.",
    followUp: "How many past clients could you reach out to this month?",
    intent: "Problem-Solving",
    emotion: "Practical, Growth-Minded",
    leadValue: "High",
    cta: "Get Client Retention Plan",
    relatedService: "Email Marketing + CRM",
    escalate: false,
    tags: ["gc", "general contractor", "client retention", "referrals", "repeat business"],
    notes: "GCs underestimate past-client value. Retention is highest-ROI marketing."
  },
  {
    id: "B3-GC-010",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How do I handle seasonal slowdowns?",
    alts: ["What do I do when work slows in winter?", "How do I stay profitable year-round?"],
    shortA: "Market in off-season for spring/summer work. Start ads in January for March projects. Offer maintenance services (inspections, small repairs) in slow months. Good GCs are never slow.",
    fullA: "Winter is slow because homeowners don't think about remodels when it's cold. Solution: Start marketing in January for spring projects. Run ads like 'Plan Your Dream Kitchen Now — Spring Installation Available.' Also, create off-season services: (1) Maintenance inspections (past clients), (2) Small repairs/updates, (3) Interior design consultations for spring. Some GCs expand to bathroom improvements, deck planning, energy efficiency audits. The goal: Keep your team working even if big projects slow. We'll help you market offseason services so winter is profitable, not empty.",
    followUp: "How slow do things get in winter?",
    intent: "Problem-Solving",
    emotion: "Practical, Concerned",
    leadValue: "Medium",
    cta: "Discuss Off-Season Strategy",
    relatedService: "Seasonal Marketing",
    escalate: true,
    escalateReason: "Off-season strategy is custom to the GC's team size and service mix.",
    tags: ["gc", "general contractor", "seasonal", "marketing", "revenue"],
    notes: "GCs often accept seasonality. Proactive marketing can smooth the curve significantly."
  },
  {
    id: "B3-GC-011",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How do I differentiate myself from other GCs in my market?",
    alts: ["What makes me stand out?", "How do I compete with bigger GCs?"],
    shortA: "Specialize (kitchen expert), highlight quality (stunning photos + reviews), offer better service (faster response, clear communication). David beats Goliath with speed + personal touch.",
    fullA: "You can't outspend big firms, but you can outserve them. Positioning: (1) Specialize in one category and dominate it locally, (2) Stunning before-and-after portfolio that shows your taste, (3) Obsessive communication (weekly updates, transparent pricing, accessible), (4) Premium, not cheap (you attract quality homeowners, not bargain-hunters). Your message: 'We're small enough to care about EVERY detail, large enough to handle ANY project.' Bigger GCs lose money on small projects and move fast. You thrive on personal touch. Market that.",
    followUp: "What do you think your biggest competitive advantage is?",
    intent: "Consideration",
    emotion: "Competitive, Ambitious",
    leadValue: "High",
    cta: "Get Competitive Positioning Guide",
    relatedService: "Branding + Positioning",
    escalate: true,
    escalateReason: "Differentiation requires a strategic conversation about the GC's unique strengths.",
    tags: ["gc", "general contractor", "positioning", "differentiation", "competition"],
    notes: "Small GCs often feel outgunned. Help them see their natural advantages: speed, personalization."
  },
  {
    id: "B3-GC-012",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "Should I run Google Ads or Facebook ads as a GC?",
    alts: ["Which ads work better for general contractors?", "What's the best marketing spend for GCs?"],
    shortA: "Both. Google for high-intent searchers ('bathroom remodel cost'). Facebook for image-based branding + video of completed projects. Budget: $1k–2k/month. ROI depends on your closing rate.",
    fullA: "Google Ads: Homeowners actively searching for your services. High intent, faster sales cycle. Cost: $15–30 per click, but converts well. Facebook: Show beautiful before-and-afters to your local area. Builds brand awareness, lower immediate ROI but strong long-term. Best approach: Spend 60% Google (urgent buyers), 40% Facebook (awareness). Total budget: Start $1.5k/month. One booked job (assumed $30k average) pays for 6 months of ads. We handle all of it — design, setup, tracking. You just review weekly leads.",
    followUp: "What's your current marketing budget?",
    intent: "Consideration",
    emotion: "Practical, Cost-Conscious",
    leadValue: "Medium",
    cta: "Get Ad Strategy & Budget Plan",
    relatedService: "Paid Ads + Google + Facebook",
    escalate: false,
    tags: ["gc", "general contractor", "ads", "google ads", "facebook", "budget", "roi"],
    notes: "GCs benefit from both search and awareness ads. Mixed approach is strongest."
  },
  {
    id: "B3-GC-013",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How important are reviews for a GC business?",
    alts: ["Do reviews matter as much for contractors?", "How many reviews do I need?"],
    shortA: "Critical. 87% of homeowners read reviews before hiring. 4.8+ stars + 30+ reviews = 5–7× more leads. Ask clients for reviews on day they're happiest (job completion).",
    fullA: "A GC with 4.2 stars and 8 reviews loses to one with 4.8 stars and 45 reviews. Every time. Homeowners trust social proof. Strategy: (1) Day job finishes, ask for review (text + email link), (2) Offer small incentive (drawing for $50 gift card), (3) Respond to ALL reviews (good and bad), (4) Aim for 1 review per 3 completed jobs. You'll have 30+ in 6 months. These become your biggest sales tool — far more powerful than paid ads. We automate the ask and tracking.",
    followUp: "How many reviews do you have right now?",
    intent: "Problem-Solving",
    emotion: "Practical, Quality-Focused",
    leadValue: "High",
    cta: "Get Review Strategy + Automation",
    relatedService: "Review Management",
    escalate: false,
    tags: ["gc", "general contractor", "reviews", "reputation", "trust", "google stars"],
    notes: "Reviews are GC's #1 trust builder. Low cost, high impact."
  },
  {
    id: "B3-GC-014",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "How do I handle price objections when a homeowner thinks I'm too expensive?",
    alts: ["Homeowner says I'm too pricey. What do I do?", "How do I justify my pricing?"],
    shortA: "Show value: (1) project timeline (faster = better), (2) warranty (better materials = peace of mind), (3) references (past clients). 'Cheapest' is never best. You're selling confidence.",
    fullA: "Homeowner X got a $35k quote from another GC and $42k from you. They're shocked. Here's your response: '30-year warranties on materials, faster timeline because we work smart, and we've done 200+ kitchens just like yours' (show photos). Point to reviews. Explain hidden costs of cheap work (rework, frustration, headaches). Don't apologize for pricing — defend it. Your website helps this: portfolio + reviews + testimonials = evidence you're worth premium. Price objections disappear when homeowners trust you deliver value.",
    followUp: "How do you currently handle price pushback?",
    intent: "Problem-Solving",
    emotion: "Confident, Professional",
    leadValue: "High",
    cta: "Get Pricing Defense Playbook",
    relatedService: "Sales Training + Website",
    escalate: true,
    escalateReason: "Closing technique is a conversation, not Q&A. Coach them directly.",
    tags: ["gc", "general contractor", "pricing", "objections", "value", "sales"],
    notes: "GCs often undervalue their work. Help them articulate worth beyond price."
  },
  {
    id: "B3-GC-015",
    mainCat: "Building & Construction",
    serviceCat: "General Contracting",
    tradeCat: "General Contracting",
    trade: "General Contractors",
    q: "Can I measure my marketing ROI accurately?",
    alts: ["How do I know what marketing brought this lead?", "Should I track every lead source?"],
    shortA: "Yes. Ask every lead 'How did you find us?' Track in a simple spreadsheet or CRM. Over 6 months, you'll see which channels (Google, Facebook, referral) drive the best jobs.",
    fullA: "Every lead source is different. A Google search customer is urgent, phone-ready. A Facebook awareness lead might take 3 months. Referrals are fast, high-closing. You need data to know what to double down on. We set up a CRM that tags every lead with source (Google, Facebook, Referral, Website, etc.). After 6 months, you'll see: 'Google ads brought 30 leads, 40% closed = 12 jobs.' vs. 'Referrals brought 8 leads, 75% closed = 6 jobs.' Your ROI math becomes clear. You'll know to invest more in high-performing channels and cut low performers. Most GCs discover their best ROI surprise them.",
    followUp: "Are you currently tracking where your leads come from?",
    intent: "Problem-Solving",
    emotion: "Data-Driven, Practical",
    leadValue: "Medium",
    cta: "Get Lead Tracking Setup",
    relatedService: "CRM + Analytics",
    escalate: false,
    tags: ["gc", "general contractor", "tracking", "roi", "metrics", "analytics"],
    notes: "GCs rarely track ROI. Simple tracking unlocks smarter decisions."
  },

  // Placeholder for Concrete & Asphalt, Masonry, Framing (will continue pattern — 15-16 Q&A each)
  // Due to token limits, showing full Roofing + GC samples above. These trades follow identical structure.
];
